angular.module('empApp',['ui.router','ngResource','empApp.controllers','empApp.services']);

angular.module('empApp').config(function($stateProvider, $httpProvider) {
    $stateProvider.state('employee',{
        url:'/employee',
        templateUrl:'partials/employee/list.html',
        controller:'EmployeeListController'
    }).state('viewEmployee',{
        url:'/eployee/:id/view',
        templateUrl:'partials/employee/view.html',
        controller:'EmployeeViewController'
    }).state('newEmployee',{
        url:'/employee/new',
        templateUrl:'partials/employee/add.html',
        controller:'EmployeeCreateController'
    }).state('editEmployee',{
        url:'/employee/:id/edit',
        templateUrl:'partials/employee/edit.html',
        controller:'EmployeeEditController'
    }).state('positions',{
        url:'/positions',
        templateUrl:'partials/positions/list.html',
        controller:'PositionsListController'
    }).state('viewPosition',{
        url:'/positions/:id/view',
        templateUrl:'partials/positions/view.html',
        controller:'PositionsViewController'
    }).state('newPosition',{
        url:'/positions/new',
        templateUrl:'partials/positions/add.html',
        controller:'PositionCreateController'
    }).state('editPosition',{
        url:'/positions/:id/edit',
        templateUrl:'partials/positions/edit.html',
        controller:'PositionEditController'
    }).state('roles',{
        url:'/roles',
        templateUrl:'partials/roles/list.html',
        controller:'RolesListController'
    }).state('viewRole',{
        url:'/roles/:id/view',
        templateUrl:'partials/roles/view.html',
        controller:'RolesViewController'
    }).state('newRole',{
        url:'/roles/new',
        templateUrl:'partials/roles/add.html',
        controller:'RoleCreateController'
    }).state('editRole',{
        url:'/roles/:id/edit',
        templateUrl:'partials/roles/edit.html',
        controller:'RoleEditController'
    }).state('login',{
        url:'/login',
        templateUrl:'partials/login/login.html',
        controller:'LoginController'
    });
}).run(function($state) {
   $state.go('login');
});